bitwise_data = {
	name: "Bitwise Ruins",
	trackHtml: "",
	art:"RUIN.jpeg",
	directory:"./Bitwise/",
	data:[
			{	name: "00000", 
				songPath: "Bitwise Ruins (0).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["00000"],
				},
			{	name: "00001", 
				songPath: "Bitwise Ruins (1).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["00001"],
				},
			{	name: "00010", 
				songPath: "Bitwise Ruins (2).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["00010"],
				},
			{	name: "00011", 
				songPath: "Bitwise Ruins (3).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["00011"],
				},
			{	name: "00100", 
				songPath: "Bitwise Ruins (4).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["00100"],
				},
			{	name: "00101", 
				songPath: "Bitwise Ruins (5).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["00101"],
				},
			{	name: "00110", 
				songPath: "Bitwise Ruins (6).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["00110"],
				},
			{	name: "00111", 
				songPath: "Bitwise Ruins (7).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["00111"],
				},
			{	name: "01000", 
				songPath: "Bitwise Ruins (8).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["01000"],
				},
			{	name: "01001", 
				songPath: "Bitwise Ruins (9).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["01001"],
				},
			{	name: "01010", 
				songPath: "Bitwise Ruins (10).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["01010"],
				},
			{	name: "01011", 
				songPath: "Bitwise Ruins (11).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["01011"],
				},
			{	name: "01100", 
				songPath: "Bitwise Ruins (12).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["01100"],
				},
			{	name: "01101", 
				songPath: "Bitwise Ruins (13).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["01101"],
				},
			{	name: "01110", 
				songPath: "Bitwise Ruins (14).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["01110"],
				},
			{	name: "01111", 
				songPath: "Bitwise Ruins (15).mp3", 
				artPath: "RUIN.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["01111"],
				},
	],
}