cv_data = {
	name: "CYBERVAMP",
	trackHtml: "",
	art:"COVER-ART.png",
	directory:"./CV/",
	data:[
			{	name: "City of Eternal Night", 
				songPath: "01 - City of Eternal Night.mp3", 
				artPath: "CITY-ENC.png",
				lyricPath: "city-of-eternal-night.html",
				tracklistData: ["City of Eternal Night"],
				},
			{	name: "Lament for Mina", 
				songPath: "02 - Lament for Mina.mp3", 
				artPath: "MINA1-1024.jpeg",
				lyricPath: "lament-for-mina.html",
				tracklistData: ["Lament for Mina"],
				},
			{	name: "ミーナへの哀歌 (Lament for Mina - JP remix)", 
				songPath: "03 - ミーナへの哀歌.mp3", 
				artPath: "MINA1-1024.jpeg",
				lyricPath: "mina-he-no-aika2.html",
				tracklistData: ["ミーナへの哀歌"," (Lament for Mina - JP remix)"],
				},
			{	name: "Dracula Online", 
				songPath: "04 - Dracula Online.mp3", 
				artPath: "DRAC-ONLINE.jpg",
				lyricPath: "dracula-online.html",
				tracklistData: ["Dracula Online"],
				},
			{	name: "Time Will Come Around", 
				songPath: "05 - Time Will Come Around.mp3", 
				artPath: "TIMEAROUND.jpg",
				lyricPath: "time-will-come-around.html",
				tracklistData: ["Time Will Come Around"],
				},
			{	name: "時が巡ってくる (Time Will Come Around - JP remix)", 
				songPath: "06 - 時が巡ってくる.mp3", 
				artPath: "TIMEAROUND.jpg",
				lyricPath: "time-will-come-around-jp.html",
				tracklistData: ["時が巡ってくる","(Time Will Come Around - JP remix)"],
				},
			{	name: "Electronic Life Intelligence Zenith Algorithm", 
				songPath: "07 - Electronic Life Intelligence Zenith Algorithm.mp3", 
				artPath: "ELIZA1.png",
				lyricPath: "eliza.html",
				tracklistData: ["Electronic Life","Intelligence Zenith Algorithm"],
				},
			{	name: "The Pride of Aries", 
				songPath: "08 - The Pride of Aries.mp3", 
				artPath: "ARIES3.png",
				lyricPath: "pride-of-aries.html",
				tracklistData: ["The Pride of Aries"],
				},
			{	name: "時が巡ってくる (Time Will Come Around - JP remix - ★BALLAD★)", 
				songPath: "09 - 時が巡ってくる - Time Will Come  Around - BALLAD.mp3", 
				artPath: "TIMEAROUNDrain.jpg",
				lyricPath: "time-will-come-around-jp-ballad.html",
				tracklistData: ["時が巡ってくる","(Time Will Come Around - JP remix - ★BALLAD★)"],
				},
		],
}