nac_data = {
	name: "Nippon and Chill",
	trackHtml: "",
	art:"NAC.jpeg",
	directory:"./NAC/",
	data:[
			{	name: "Track (01)", 
				songPath: "Nippon and Chill (1).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (01)"],
				},
			{	name: "Track (02)", 
				songPath: "Nippon and Chill (2).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (02)"],
				},
			{	name: "Track (03)", 
				songPath: "Nippon and Chill (3).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (03)"],
				},
			{	name: "Track (04)", 
				songPath: "Nippon and Chill (4).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (04)"],
				},
			{	name: "Track (05)", 
				songPath: "Nippon and Chill (5).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (05)"],
				},
			{	name: "Track (06)", 
				songPath: "Nippon and Chill (6).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (06)"],
				},
			{	name: "Track (07)", 
				songPath: "Nippon and Chill (7).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (07)"],
				},
			{	name: "Track (08)", 
				songPath: "Nippon and Chill (8).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (08)"],
				},
			{	name: "Track (09)", 
				songPath: "Nippon and Chill (9).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (09)"],
				},
			{	name: "Track (10)", 
				songPath: "Nippon and Chill (10).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (10)"],
				},
			{	name: "Track (11)", 
				songPath: "Nippon and Chill (11).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (11)"],
				},
			{	name: "Track (12)", 
				songPath: "Nippon and Chill (12).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (12)"],
				},
			{	name: "Track (13)", 
				songPath: "Nippon and Chill (13).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (13)"],
				},
			{	name: "Track (14)",
				songPath: "Nippon and Chill (14).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (14)"],
				},
			{	name: "Track (15)",
				songPath: "Nippon and Chill (15).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (15)"],
				},
			{	name: "Track (16)", 
				songPath: "Nippon and Chill (16).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (16)"],
				},
			{	name: "Track (17)", 
				songPath: "Nippon and Chill (17).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (17)"],
				},
			{	name: "Track (18)", 
				songPath: "Nippon and Chill (18).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (18)"],
				},
			{	name: "Track (19)", 
				songPath: "Nippon and Chill (19).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (19)"],
				},
			{	name: "Track (20)", 
				songPath: "Nippon and Chill (20).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (20)"],
				},
			{	name: "Track (21)", 
				songPath: "Nippon and Chill (21).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (21)"],
				},
			{	name: "Track (22)", 
				songPath: "Nippon and Chill (22).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (22)"],
				},
			{	name: "Track (23)", 
				songPath: "Nippon and Chill (23).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (23)"],
				},
			{	name: "Track (24)", 
				songPath: "Nippon and Chill (24).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (24)"],
				},
			{	name: "Track (25)", 
				songPath: "Nippon and Chill (25).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (25)"],
				},
			{	name: "Track (26)", 
				songPath: "Nippon and Chill (26).mp3", 
				artPath: "NAC.jpeg",
				lyricPath: "blank.html",
				tracklistData: ["Track (26)"],
				},
	],
}