tbs_data = {
	name: "THE BLACK SPHINX",
	trackHtml: "",
	art:"TBS-COVER.png",
	directory:"./TBS/",
	data:[
			{	name: "Secrets of the Ancients", 
				songPath: "Secrets of the Ancients.mp3", 
				artPath: "SECRETS.jpeg",
				lyricPath: "secrets-of-the-ancients.html",
				tracklistData: ["Secrets of the Ancients"],
				},
			{	name: "The Eye of the Storm", 
				songPath: "The Eye of the Storm.mp3", 
				artPath: "STORM.jpeg",
				lyricPath: "the-eye-of-the-storm.html",
				tracklistData: ["The Eye of the Storm"],
				},
			// {	name: "The Black Sphinx", 
			// 	songPath: "The Black Sphinx.mp3", 
			// 	artPath: "SPHINX.jpeg",
			// 	lyricPath: "the-black-sphinx.html",
			// 	tracklistData: ["The Black Sphinx"],
			// 	},
			{	name: "The Black Sphinx", 
				songPath: "The Black Sphinx - Clubmix.mp3", 
				artPath: "SPHINX.jpeg",
				lyricPath: "the-black-sphinx.html",
				tracklistData: ["The Black Sphinx"],
				},
			{	name: "Vox Regis non sunt Vox Populi", 
				songPath: "Vox Regis non sunt Vox Populi.mp3", 
				artPath: "VOX.png",
				lyricPath: "vox-regis-non-sunt-vox-populi.html",
				tracklistData: ["Vox Regis non sunt Vox Populi"],
				},
			{	name: "Desert of Glass", 
				songPath: "Desert of Glass.mp3", 
				artPath: "GLASS.png",
				lyricPath: "desert-of-glass.html",
				tracklistData: ["Desert of Glass"],
				},

		],
}